version: "3.1"

services:

    www:
        build: .
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
            
    db:
        image: mysql:8.0
        expose: 
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./database/db-dump:/docker-entrypoint-initdb.d
            - ./mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 

